[build]
builder = "NIXPACKS"
buildCommand = "npm run build && npm run migrate:deploy"

[deploy]
startCommand = "cd apps/api && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
