[build]
builder = "NIXPACKS"
buildCommand = "npm ci --include=dev && npm run build:shared && npm run build:api"

[deploy]
startCommand = "cd apps/api && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
