[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "cd apps/api && npx prisma migrate deploy && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
